global:
  scrape_interval: 5s # 压测时建议设短一点，默认是 1m，5s 能看到更实时的波动

scrape_configs:
  - job_name: 'dawn-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['dawn-app:8080'] 
        # Docker 容器服务名，Docker Compose 会自动解析
        # 如果你的 Spring Boot 端口不是 8080，请修改这里