server:
  port: 8080

spring:
  application:
    name: dawn

  profiles:
    active: dev # 或者prod

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/dawn?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  data:
    redis:
      host: redis
      port: 6379
      password: 123456
      database: 1
      lettuce:
        pool:
          min-idle: 10
          max-idle: 100
          max-active: 100
          max-wait: 10000

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: 123456
    virtual-host: dawn
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

  elasticsearch:
    uris: elasticsearch:9200

  mail:
    host: smtp.163.com
    username: ${SPRING_MAIL_USERNAME:邮箱}
    password: ${SPRING_MAIL_PASSWORD:密码}
    port: 465 # 对于 SSL 连接
    protocol: smtps # 使用 ssl
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true # 启用 SSL
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          timeout: 5000
          connectiontimeout: 5000

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

search:
  mode: elasticsearch

upload:
  mode: minio
  minio:
    url: http://minio:9000/
    endpoint: http://minio:9000
    externalEndpoint: http://127.0.0.1:9000/test/
    accesskey: minioadmin
    secretKey: Dududu951221
    bucketName: test

# 百度SEO推送使用，由于暂无公网域名，对应的background job无法正常工作
website:
  url: http://localhost:8082

qq:
  app-id: QQ APPID
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}

logging:
  file:
    name: /logs/app.log # name 优先级大于 path
#    path: /var/logs/myapp
  level:
    root: INFO
    com:
      dawn: DEBUG
    # org.springframework.security: DEBUG
    # org.springframework.amqp: DEBUG
    com.baomidou.mybatisplus: DEBUG

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  health:
#    show-details: always
#    mail:
#      enabled: false  # 禁用邮件健康检查

#management:
#  endpoints:
#    enabled-by-default: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info # 暴露 prometheus 端点
  metrics:
    tags:
      application: ${spring.application.name} # 给所有指标加个标签
  
  tracing:
    sampling:
      probability: 1 # 100 的采样率, 生产环境建议调整为 0.1 或更低